
## Author: Amal Joseph Varghese
## Configuration for Total Segmentator (TS).
## The roi_subsets to be delineated using the `total` model of TS..

roi_subset:
# Mediastenum

- esophagus
- trachea

# Heart & Gteat Vessels (task="totak")

- heart
- pulmonary_vein
- superior_vena_cava
- inferior_vena_cava
- atrial_appendage_left
- aorta

# Lower Body

- spleen
- liver

# Small Vessels

- subclavian_artery_right
- subclavian_artery_left
- brachiocephalic_trunk
- common_carotid_artery_right
- common_carotid_artery_left
- brachiocephalic_vein_right
- brachiocephalic_vein_left

# Lungs

- lung_lower_lobe_left
- lung_lower_lobe_right
- lung_middle_lobe_right
- lung_upper_lobe_left
- lung_upper_lobe_right

# Bony Structures

- humerus_left
- humerus_right
- clavicula_right
- clavicula_left
- scapula_right
- scapula_left
- sternum

- rib_left_1
- rib_left_2
- rib_left_3
- rib_left_4
- rib_left_5
- rib_left_6
- rib_left_7
- rib_left_8
- rib_left_9
- rib_left_10
- rib_left_11
- rib_left_12
- rib_right_1
- rib_right_2
- rib_right_3
- rib_right_4
- rib_right_5
- rib_right_6
- rib_right_7
- rib_right_8
- rib_right_9
- rib_right_10
- rib_right_11
- rib_right_12

- vertebrae_C1
- vertebrae_C2
- vertebrae_C3
- vertebrae_C4
- vertebrae_C5
- vertebrae_C6
- vertebrae_C7
- vertebrae_T1
- vertebrae_T2
- vertebrae_T3
- vertebrae_T4
- vertebrae_T5
- vertebrae_T6
- vertebrae_T7
- vertebrae_T8
- vertebrae_T9
- vertebrae_T10
- vertebrae_T11
- vertebrae_T12
- vertebrae_L1
- vertebrae_L2
- vertebrae_L3
- vertebrae_L4
- vertebrae_L5
- sacrum
- vertebrae_S1
